### ISSUE TITLE
Table: Bugs and Feature requests

### ISSUE THREAD

**Issue by amitb01** [innovaccer/design-system#246]
- [ ] Hide nested row trigger icon when there is no nested child of a parent (to be discussed with design team, design screen attached)
- [ ] Disable nested row scrolling horizontally independent of parent (issue screenshot attached)
- [ ] Add (cursor:pointer) to nested row trigger icon on parent row
- [ ] Give option to hide pagination dynamically or when fetched results are less than defined page count
- [ ] Fix spacing issues due to overflow-x on table footer
- [ ] If loadingSchema is not provided, the loading key in cell prop is always false. Hence cannot show loading state in cell
- [ ] Give the option to set empty search template when a search returns 0 results (like error template)
- [ ] Increase the debounce delay from 250ms to a higher value or expose a prop to set the same
- [ ] Give an option to set “Showing x items” count in the table header. This is required because the result count currently does not take into account the nested results.

<img width="1014" alt="Screenshot 2020-07-24 at 7 39 05 PM" src="https://user-images.githubusercontent.com/13330942/88475889-a07bf400-cf51-11ea-884b-3331b67622d5.png">

<img width="915" alt="Screenshot 2020-07-26 at 2 55 49 PM" src="https://user-images.githubusercontent.com/13330942/88475892-a5d93e80-cf51-11ea-8b06-9efc6ee0f6a8.png">

**Comment by aditya-kumawat** [comment]
#### Already done:
- Add (cursor:pointer) to nested row trigger icon on parent row
- Fix spacing issues due to overflow-x on table footer

#### To be done:
- Disable nested row scrolling horizontally independent of parent 
- Give option to hide pagination dynamically or when fetched results are less than defined page count
- Give the option to set empty search template when a search returns 0 results

#### Not supposed to be done:
- Hide nested row trigger icon when there is no nested child of a parent (to be discussed with design team, design screen attached)

#### More info on issues required:
- If loadingSchema is not provided, the loading key in cell prop is always false. Hence cannot show loading state in cell
- Increase the debounce delay from 250ms to a higher value or expose a prop to set the same
- Give an option to set “Showing x items” count in the table header. This is required because the result count currently does not take into account the nested results.

**Comment by satyamyadav** [comment]
- [ ] Give the option to set empty search template when a search returns 0 results `InProgress` in #279 . 
- [x] Increase the debounce delay from 250ms to a higher value or expose a prop to set the same. `this should not be done as it should be consistent across system`.
