### ISSUE TITLE
Dropdown  key mapping

### ISSUE THREAD

**Issue by dhananjay-innovaccer** [innovaccer/design-system#750]
In dropdown pls provide the feature for mapping label and value to other keywords(suitable to dev).

Ex -lableKey ={Name}, valueKey(id)

After this config dropdown must map name as label and id as their corresponding value

**Comment by veekays** [comment]
@dhananjay-innovaccer This feature wouldn't be possible in DropDown because this might break things inside the component. Dropdown options schema is defined in such a way to have label and value as key in TypeScript.

In order to have this functionality you have to map the labelKey and valueKey to desired key at your end.
