### ISSUE TITLE
Sorting UI issue

### ISSUE THREAD

**Issue by dhananjay-innovaccer** [innovaccer/design-system#805]
**Below issue is occured in grid component**
1. Ascending arrow should be up and descending arrow should be down on sorting in the column header.
2. On hover on the column header, the cursor should be a hand tool if it has a sorting feature

**Comment by Gautam-Arora24** [comment]
Can I work on this issue?
@dhananjay-innovaccer

**Comment by veekays** [comment]
@Gautam-Arora24 If you want to work on this then i can give you some context regarding what needs to be done.

**Comment by Gautam-Arora24** [comment]
That would be great @veekays

**Comment by veekays** [comment]
@Gautam-Arora24 So the issue is mentioned above by @dhananjay-innovaccer, Here are the things you need to start working on this.
Design:- https://design.innovaccer.com/0ee0e5c39/v/0/p/77fb5b-table/b/10a569
Component:- https://innovaccer.github.io/design-system/?path=/docs/patterns-table-table-with-header--table-with-header

**Comment by Gautam-Arora24** [comment]
Thanks for the context. I will start working on this :)

**Comment by veekays** [comment]
@Gautam-Arora24 Any update on this?

**Comment by Gautam-Arora24** [comment]
Hi @veekays! Sorry for the late reply. I haven't yet started working on this issue. I'll let you know when I will start :)
